// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function isValidSupabaseKey(key: string): boolean {
  return key.startsWith("eyJ") || isNewSupabaseApiKey(key);
}

function isValidHttpUrl(url: string | undefined | null): boolean {
  if (!url || typeof url !== "string") return false;
  const trimmed = url.trim();
  if (!trimmed.startsWith("http://") && !trimmed.startsWith("https://")) {
    return false;
  }
  try {
    const parsed = new URL(trimmed);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    if (!isValidSupabaseKey(supabaseKey)) {
      // Local offline mode or placeholder key: return clean response to use local fallback seamlessly
      const urlString =
        typeof input === "string" ? input : input instanceof Request ? input.url : "";
      const body = urlString.includes("/auth/v1") ? { user: null, session: null } : [];
      return new Response(JSON.stringify(body), {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Content-Range": "0-0/0",
        },
      });
    }

    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    try {
      const response = await fetch(input, { ...init, headers });
      if (response.status === 401) {
        const urlString =
          typeof input === "string" ? input : input instanceof Request ? input.url : "";
        const body = urlString.includes("/auth/v1") ? { user: null, session: null } : [];
        return new Response(JSON.stringify(body), {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "Content-Range": "0-0/0",
          },
        });
      }
      return response;
    } catch (err) {
      const urlString =
        typeof input === "string" ? input : input instanceof Request ? input.url : "";
      const body = urlString.includes("/auth/v1") ? { user: null, session: null } : [];
      return new Response(JSON.stringify(body), {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Content-Range": "0-0/0",
        },
      });
    }
  };
}

function createSupabaseClient() {
  const DEFAULT_SUPABASE_URL = "https://myqtvbfibvgxkqwxvuru.supabase.co";
  const MYQTV_PROJECT_REF = "myqtvbfibvgxkqwxvuru";
  const MYQTV_ANON_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cXR2YmZpYnZneGtxd3h2dXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4MjY0NjgsImV4cCI6MjEwMDQwMjQ2OH0.LDFW826N2GRzG9WnLHgYxoeOcTkDOeLjTiFK6aQ-BSE";

  const rawUrlCandidates = [
    typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env.VITE_SUPABASE_URL
      : undefined,
    typeof process !== "undefined" && process.env ? process.env.VITE_SUPABASE_URL : undefined,
    typeof process !== "undefined" && process.env ? process.env.SUPABASE_URL : undefined,
  ];

  let SUPABASE_URL = rawUrlCandidates.find(isValidHttpUrl) || DEFAULT_SUPABASE_URL;

  let SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
      : undefined) ||
    (typeof process !== "undefined" && process.env
      ? process.env.VITE_SUPABASE_ANON_KEY ||
        process.env.SUPABASE_ANON_KEY ||
        process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
        process.env.SUPABASE_PUBLISHABLE_KEY
      : undefined);

  // If the key was mistakenly provided as a URL or is missing/invalid, fallback to default key
  if (
    !SUPABASE_PUBLISHABLE_KEY ||
    SUPABASE_PUBLISHABLE_KEY.startsWith("http://") ||
    SUPABASE_PUBLISHABLE_KEY.startsWith("https://")
  ) {
    SUPABASE_PUBLISHABLE_KEY = MYQTV_ANON_KEY;
  }

  // If connected to myqtvbfibvgxkqwxvuru, ensure the key belongs to this project ref (prevent stale env tokens from other projects)
  if (
    SUPABASE_URL.includes(MYQTV_PROJECT_REF) &&
    (!SUPABASE_PUBLISHABLE_KEY || !SUPABASE_PUBLISHABLE_KEY.includes(MYQTV_PROJECT_REF))
  ) {
    SUPABASE_PUBLISHABLE_KEY = MYQTV_ANON_KEY;
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    SUPABASE_PUBLISHABLE_KEY = MYQTV_ANON_KEY;
  }

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please check your environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const customStorage =
    typeof window !== "undefined"
      ? {
          getItem: (key: string) => {
            return window.localStorage.getItem(key) || window.sessionStorage.getItem(key);
          },
          setItem: (key: string, value: string) => {
            if (window.localStorage.getItem("remember_me") === "true") {
              window.localStorage.setItem(key, value);
            } else {
              window.sessionStorage.setItem(key, value);
            }
          },
          removeItem: (key: string) => {
            window.localStorage.removeItem(key);
            window.sessionStorage.removeItem(key);
          },
        }
      : undefined;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: customStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
